# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
testnets-settings:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: ethereum-testnet-sepolia-optimism-1
      url: https://optimism-sepolia-rpc.publicnode.com
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://base-sepolia-rpc.publicnode.com
mainnets-settings:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com
