# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================

production-settings:
  user-workflow:
    workflow-name: "blockhash-relay"
    deployment-registry: "onchain:ethereum-mainnet"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""
